revolver:
  mailBox:
    type: in_memory
  clientConfig:
    clientName: revolver-api
  services:
    - type: http
      service: mocky
      connectionPoolSize: 5
      connectionKeepAliveInMillis: 60000
      authEnabled: false
      endpoint:
        type: simple
        host: 192.168.99.100
        port: 3000
      apis:
        - api: ping
          async: false
          path: "user/{id}"
          methods:
            - GET
          runtime:
            threadPool:
              concurrency: 5
              timeout: 10000
